GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjksIm5hbWUiOiJTYWRyYSIsImVtYWlsIjoiU2FkcmFheml6aTEzMDVAZ21haWwuY29tIiwiaWF0IjoxNzI5MTAzNTI0LCJleHAiOjE3MjkxMDM1NDR9.yBmDIhslphLaSAQYeqi7N2KJQiVUZDcNMjZcdCMMCDk

###
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "Sadra",
    "email": "Sadraazizi1305@gmail.com",
    "password": "GajahTerbang",
    "confPassword": "GajahTerbang"
}


###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "Sadraazizi1305@gmail.com",
    "password": "GajahTerbang"
}

###
GET http://localhost:5000/token

###
DELETE http://localhost:5000/logout